### ISSUE TITLE
[RFC] Typings

### ISSUE THREAD

**Issue by Bernardoow** [flask-extensions/Flask-GoogleMaps#106]
**Is your feature request related to a problem? Please describe.**
This is not a problemn but a just a enhancement to reads of the code.

**Describe the solution you'd like**
The suggestion is to put the type os variables on the code. This suggestion is follwing the [PEP 484 - Type Hints](https://www.python.org/dev/peps/pep-0484/).

Example ->

`def plus(x, y):` **to** `def plus(x: float, y: float) -> float:`

**Additional context**
https://docs.python.org/3/library/typing.html

**Comment by Entitet** [comment]
This feature request seems to have been adressed. Can this issue be considered resolved, or are there still some enhancement to be made?
