### ISSUE TITLE
Can you customize how the maps look?

### ISSUE THREAD

**Issue by ghltshubh** [flask-extensions/Flask-GoogleMaps#109]

**Comment by louisromano** [comment]
Hey, just figured it out.  Hopefully it will help others.  

go here https://mapstyle.withgoogle.com/

copy the JSON.

edit the lib/site-packages/flask_googlemaps/templates/gmapjs.html 

look for these lines:
            rotateControl: {% if gmap.rotate_control %}true{% else %}false{% endif %},
            scrollwheel: {% if gmap.scroll_wheel %}true{% else %}false{% endif %},
            fullscreenControl: {% if gmap.fullscreen_control %}true{% else %}false{% endif %},

****NOTE**** YOU HAVE TO ADD THE COMMA to the end of fullscreenControl line.

then add styles: [copied JSON code]

so it will look like this:

            rotateControl: {% if gmap.rotate_control %}true{% else %}false{% endif %},
            scrollwheel: {% if gmap.scroll_wheel %}true{% else %}false{% endif %},
            fullscreenControl: {% if gmap.fullscreen_control %}true{% else %}false{% endif %},
            styles: [
  {
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#f5f5f5"
      }
    ]
  },
  {
    "elementType": "labels.icon",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  },
  {
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#616161"
      }
    ]
  },
  {
    "elementType": "labels.text.stroke",
    "stylers": [
      {
        "color": "#f5f5f5"
      }
    ]
  },
  {
    "featureType": "administrative.land_parcel",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#bdbdbd"
      }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#eeeeee"
      }
    ]
  },
  {
    "featureType": "poi",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#757575"
      }
    ]
  },
  {
    "featureType": "poi.park",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#e5e5e5"
      }
    ]
  },
  {
    "featureType": "poi.park",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#9e9e9e"
      }
    ]
  },
  {
    "featureType": "road",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#ffffff"
      }
    ]
  },
  {
    "featureType": "road.arterial",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#757575"
      }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#dadada"
      }
    ]
  },
  {
    "featureType": "road.highway",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#616161"
      }
    ]
  },
  {
    "featureType": "road.local",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#9e9e9e"
      }
    ]
  },
  {
    "featureType": "transit.line",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#e5e5e5"
      }
    ]
  },
  {
    "featureType": "transit.station",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#eeeeee"
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "geometry",
    "stylers": [
      {
        "color": "#c9c9c9"
      }
    ]
  },
  {
    "featureType": "water",
    "elementType": "labels.text.fill",
    "stylers": [
      {
        "color": "#9e9e9e"
      }
    ]
  }
]

**Comment by marloncard** [comment]
In case anyone still has this question and doesn't want to modify the package, just add the following to your template:

```
<body onload="appendStyle()">
    ....
</body>
<script>
  function appendStyle(){
    const myStyle = [ {
        "elementType": "geometry",
        "stylers": [
          {
            "color": "#212121"
          }... ];
    map.setOptions({styles:myStyle});
  }
</script>
```

**Comment by bhuveshsharma09** [comment]
Hey,
I would like to enhance this feature and add new attribute 'styles'.
The user will be able to add a custom style JSON file to the map through 'styles' attribute while initializing the map.

For example the below given 'Dark Mode'
![image](https://user-images.githubusercontent.com/62707309/94388283-22211580-017f-11eb-8938-74e29e5b9d04.png)
