### ISSUE TITLE
[RFC] Add KML layer on the Map

### ISSUE THREAD

**Issue by bhuveshsharma09** [flask-extensions/Flask-GoogleMaps#131]
I would like to develop a piece of code for this repo which will help user to add KML layers on the map.

While initializing a map object, the user will be able to pass a KML file, Which will appear on the map as a layer

For example, the KML layer of dengue spread in Singapore.

![image](https://user-images.githubusercontent.com/62707309/94388708-78db1f00-0180-11eb-943e-12e07dd2abe8.png)

**Comment by JacobGeoGeek** [comment]
@Riverfount, can we close this issue?
