### ISSUE TITLE
[RFC] Heatmaps 

### ISSUE THREAD

**Issue by getcake** [flask-extensions/Flask-GoogleMaps#147]
Not an issue but I think it'd be cool to have a heatmap feature! 

Looking at the [heatmap overlay example](https://developers.google.com/maps/documentation/javascript/examples/layer-heatmap) from the visualization library, would this be possible? 

I've looked into creating this feature myself but I'm pretty new to python and flask in general. In the meantime I've been working with [heatmaps.py](http://jjguy.com/heatmap/) for this, but I think it'd be really sweet to have this as a built-in functionality. 

I'll continue trying to implement this myself for my own project, but I just wanted to put it out there.

**Comment by JacobGeoGeek** [comment]
Can we close this Issue?
