### ISSUE TITLE
Style parameter non-responsive

### ISSUE THREAD

**Issue by bsgilber** [flask-extensions/Flask-GoogleMaps#54]
I am invoking the Map class, trying to modify the style variable, but I'm not seeing any response in the output. Do you have any additional examples you could provide? My code below, any help would be appreciated!

From my app/__init__.py:
```Python
@app.route("/", methods=['POST','GET'])
def main():
	sndmap = Map(
		identifier="sndmap",
		lat=33.753746,
                lng=-84.386330,
                style="height:200px;width:200px:margin:0;",  # <---
                ....
                )
        return render_template('index.html', sndmap=sndmap)
```

From my html file:
```html
<head>
    ....
    {{sndmap.js}}
</head>

<section>
    <center>
    {{sndmap.html}}
    <p></p>
    <ul class="actions">
        <li><a href="/learnmore" class="button alt">Learn More</a></li>
    </ul>
    </center>
</section>
````

**Comment by Itisfilipe** [comment]
I noticed that there's a typo in your code (: should be ; after width:200px)

`style="height:200px;width:200px:margin:0;",  # <---`

should be 

`style="height:200px;width:200px;margin:0;",  # <---`

let me know if you still can't change the styles =)
